import {useEffect,useMemo,useState,type ReactNode} from "react";
import {SessionRenderer} from "@agentour/react";
import {AgentourShell,AgentCard,PageHeader,Panel,MetricCard,DataTable,LoadingState,EmptyState,Badge} from "@agentour/ui";
import "@agentour/ui/styles.css";
import {AgentourClient,tokenFromEndpoint,type Agent,type LibraryItem,type Session,type TenantContext} from "./api";
import {portalConfig} from "./config";
import "./styles.css";

type Tab="discover"|"workspace"|"library"|"publish"|"billing"|"channels"|"admin";
const tabs:{id:Tab;label:string;icon:string;admin?:boolean}[]=[
 {id:"discover",label:"发现",icon:"✦"},{id:"workspace",label:"工作台",icon:"▣"},{id:"library",label:"资料库",icon:"▤"},
 {id:"publish",label:"我的发布",icon:"↑"},{id:"billing",label:"账单",icon:"◉"},{id:"channels",label:"渠道",icon:"⌁"},{id:"admin",label:"租户管理",icon:"◆",admin:true}];
const descriptions:Record<Tab,string>={discover:"浏览租户已获配的 Agent 与 AIO，查看详情后即可使用。",workspace:"会话、运行状态、审批与交付物集中在这里。",library:"管理供 Agent 使用的资料与成果。",publish:"管理个人私有与租户内公开的 Agent Package。",billing:"按 Session 查看个人用量与租户归因。",channels:"查看飞书安装、绑定和渠道状态。",admin:"仅查看当前租户范围内的管理数据。"};

export default function App(){
 const config=useMemo(()=>portalConfig(),[]),client=useMemo(()=>new AgentourClient(config,()=>tokenFromEndpoint(config.tokenEndpoint)),[config]);
 const [context,setContext]=useState<TenantContext|null>(null),[agents,setAgents]=useState<Agent[]>([]),[tab,setTab]=useState<Tab>("discover"),[error,setError]=useState(""),[busy,setBusy]=useState(true),[sessionId,setSessionId]=useState("");
 const isAdmin=Boolean(context?.scopes.some(scope=>scope.startsWith("tenant:")));
 useEffect(()=>{document.documentElement.style.setProperty("--primary",config.primaryColor);let cancelled=false;void(async()=>{for(let attempt=0;attempt<12;attempt++)try{const [ctx,list]=await Promise.all([client.context(),client.agents()]);if(!cancelled){setContext(ctx);setAgents(list.data);setBusy(false)}return}catch(e){if(attempt===11&&!cancelled){setError(String(e));setBusy(false);return}await new Promise(r=>setTimeout(r,Math.min(1000*(attempt+1),5000)))}})();return()=>{cancelled=true}},[client,config]);
 if(busy)return <main className="center"><LoadingState label="正在进入租户工作区…"/></main>;
 if(error)return <main className="center"><section className="error"><h1>无法进入门户</h1><p>{error}</p><small>身份端点：{config.tokenEndpoint}</small></section></main>;
 const visible=tabs.filter(x=>!x.admin||isAdmin),meta=visible.find(x=>x.id===tab)!;
 return <AgentourShell brand={context?.tenant.name||config.brandName} subtitle="Agent 平台" items={visible} active={tab} onNavigate={id=>{setSessionId("");setTab(id as Tab)}} balance={<><small>租户余额</small><strong>{context?.tenant.balance_credits?.toLocaleString()||0} 积分</strong></>} identity={<div className="tenant-identity"><b>{context?.subject_id?"内部用户":"管理会话"}</b><small>{context?.subject_id||context?.actor_type}</small></div>} headerActions={<Badge tone="success">租户已连接</Badge>}>
  <PageHeader eyebrow="用户工作区" title={sessionId?"Session":meta.label} description={sessionId?"与平台一致的运行、审批、输入和交付体验。":descriptions[tab]}/>
  <div className="agentour-content">{sessionId?<SessionView id={sessionId} client={client} onBack={()=>setSessionId("")}/>:<Page tab={tab} agents={agents} client={client} openSession={setSessionId}/>}</div>
 </AgentourShell>;
}

function Page({tab,agents,client,openSession}:{tab:Tab;agents:Agent[];client:AgentourClient;openSession:(id:string)=>void}){
 if(tab==="discover")return <Discover agents={agents} client={client} onOpen={openSession}/>;
 if(tab==="workspace")return <Workspace client={client} onOpen={openSession}/>;
 if(tab==="library")return <Library client={client}/>;
 if(tab==="publish")return <Publishing client={client}/>;
 if(tab==="billing")return <Billing client={client}/>;
 if(tab==="channels")return <Channels client={client}/>;
 return <Admin client={client}/>;
}

function Discover({agents,client,onOpen}:{agents:Agent[];client:AgentourClient;onOpen:(id:string)=>void}){
 const [query,setQuery]=useState(""),[tag,setTag]=useState(""),[detail,setDetail]=useState<Agent|null>(null),[message,setMessage]=useState("");
 const tags=[...new Set(agents.flatMap(a=>a.tags||[]))].slice(0,12),rows=agents.filter(a=>(!query||`${a.name} ${a.description} ${(a.tags||[]).join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(!tag||(a.tags||[]).includes(tag)));
 const aio=rows.filter(a=>a.kind==="workflow"||a.kind==="aio"),experts=rows.filter(a=>!aio.includes(a));
 const run=(agent:Agent)=>client.createSession(agent.id).then(x=>onOpen(x.session_id)).catch(e=>setMessage(String(e)));
 return <><div className="discover-search"><span>⌕</span><input aria-label="搜索 Agent" placeholder="搜索 Agent、AIO 或行业…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-row"><button className={!tag?"active":""} onClick={()=>setTag("")}>全部</button>{tags.map(x=><button key={x} className={tag===x?"active":""} onClick={()=>setTag(tag===x?"":x)}>{x}</button>)}</div>{aio.length>0&&<CatalogSection title="AIO" subtitle="多 Agent 协作并整理为完整交付物" rows={aio} open={setDetail} run={run}/>}<CatalogSection title="专家 Agent" subtitle="Agent 各自完成单一职责" rows={experts} open={setDetail} run={run}/>{message&&<p className="error-text">{message}</p>}{detail&&<AgentDetail agent={detail} close={()=>setDetail(null)} run={()=>run(detail)}/>}</>;
}
function CatalogSection({title,subtitle,rows,open,run}:{title:string;subtitle:string;rows:Agent[];open:(a:Agent)=>void;run:(a:Agent)=>void}){return <section className="catalog-section"><div className="section-title"><div><h2>{title}</h2><p>{subtitle}</p></div><span>{rows.length} 个可用</span></div>{rows.length?<div className="agentour-grid">{rows.map(a=><AgentCard key={a.id} agent={a} onOpen={()=>open(a)} onRun={()=>run(a)}/>)}</div>:<EmptyState title={`暂无${title}`}/>}</section>}
function AgentDetail({agent,close,run}:{agent:Agent;close:()=>void;run:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="agent-detail"><button className="modal-close" aria-label="关闭" onClick={close}>×</button><div className="detail-hero"><div className="detail-icon">{agent.icon||"A"}</div><div><Badge>{agent.kind==="workflow"?"AIO":"Agent"}</Badge><h2>{agent.name}</h2><p>{agent.description||"租户可用 Agent"}</p></div></div><div className="detail-block"><h3>能力标签</h3><div className="filter-row">{(agent.tags||[]).map(t=><span key={t}>{t}</span>)}</div></div><div className="detail-block"><h3>快速开始</h3><p>创建独立 Session，在工作台继续查看运行、审批与交付物。</p></div><footer><button className="secondary" onClick={close}>取消</button><button className="primary" onClick={run}>开始使用</button></footer></section></div>}

function Workspace({client,onOpen}:{client:AgentourClient;onOpen:(id:string)=>void}){const [rows,setRows]=useState<Session[]|null>(null),[state,setState]=useState("");useEffect(()=>{client.sessions().then(x=>setRows(x.data)).catch(()=>setRows([]))},[client]);if(!rows)return <LoadingState/>;const filtered=rows.filter(x=>!state||x.state===state),running=rows.filter(x=>!["completed","failed","cancelled"].includes(x.state)).length;return <><div className="agentour-metrics"><MetricCard label="全部会话" value={rows.length}/><MetricCard label="运行中" value={running}/><MetricCard label="累计消耗" value={rows.reduce((n,x)=>n+(x.spent||0),0)} detail="积分"/></div><Panel title="我的会话" description="只显示当前内部用户的私有 Session" actions={<select value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option>{[...new Set(rows.map(x=>x.state))].map(x=><option key={x}>{x}</option>)}</select>}><DataTable headers={["会话","Agent","状态","更新时间","消耗","操作"]} rows={filtered.map(x=>[x.title||x.id,x.agent_id,<Badge tone={x.state==="completed"?"success":x.state==="failed"?"danger":"warning"}>{x.state}</Badge>,date(x.updated_at),`${x.spent||0} 积分`,<button className="link-button" onClick={()=>onOpen(x.id)}>打开</button>])}/></Panel></>}

function SessionView({id,client,onBack}:{id:string;client:AgentourClient;onBack:()=>void}){const [data,setData]=useState<any>(),[text,setText]=useState(""),[error,setError]=useState("");const load=()=>Promise.all([client.session(id),client.presentation(id),client.artifacts(id),client.attachments(id)]).then(([session,presentation,artifacts,attachments])=>setData({session,presentation,artifacts,attachments})).catch(e=>setError(String(e)));useEffect(()=>{void load()},[id]);return <><button className="back" onClick={onBack}>← 返回工作台</button><div className="session-grid"><Panel className="session-main">{error&&<p className="error-text">{error}</p>}{data?.presentation?<SessionRenderer presentation={data.presentation} onCancel={()=>client.cancel(id).then(load)} onRetry={load} onSubmitInteraction={(interaction,values)=>interaction.kind==="approval"?client.approve(id,interaction,"approve").then(load):client.submit(id,interaction,values).then(load)}/>:<LoadingState/>}<form className="composer" onSubmit={e=>{e.preventDefault();if(text)void client.sendMessage(id,text).then(()=>{setText("");return load()}).catch(e=>setError(String(e)))}}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="给 Agent 发送消息"/><button>发送</button></form></Panel><Panel title="附件与交付物"><ResourceList items={data?.attachments?.data} empty="暂无附件"/><ResourceList items={data?.artifacts?.data} empty="暂无交付物"/></Panel></div></>}
function ResourceList({items,empty}:{items:any[];empty:string}){return items?.length?<ul className="resource-list">{items.map((x,i)=><li key={x.id||i}><span>▧</span><div><b>{x.name||x.title||x.id}</b><small>{x.mime||x.status||""}</small></div></li>)}</ul>:<p className="muted">{empty}</p>}

function Library({client}:{client:AgentourClient}){const [rows,setRows]=useState<LibraryItem[]|null>(null),[query,setQuery]=useState("");useEffect(()=>{client.library().then(x=>setRows(x.data)).catch(()=>setRows([]))},[client]);if(!rows)return <LoadingState/>;const filtered=rows.filter(x=>!query||(x.title||x.name||x.id).toLowerCase().includes(query.toLowerCase()));return <Panel title="我的资料" description="资料与交付物均按当前内部用户隔离" actions={<div className="panel-actions"><input placeholder="搜索资料" value={query} onChange={e=>setQuery(e.target.value)}/></div>}><DataTable headers={["名称","来源","状态","更新时间"]} rows={filtered.map(x=>[x.title||x.name||x.id,x.origin_kind||"上传",<Badge tone="success">可用</Badge>,date(x.updated_at)])}/></Panel>}

function Publishing({client}:{client:AgentourClient}){const [visibility,setVisibility]=useState<"private"|"public">("private"),[message,setMessage]=useState(""),[activity,setActivity]=useState<any>();useEffect(()=>{client.publishingActivity().then(setActivity).catch(()=>setActivity({}))},[client]);const jobs=activity?.publish_jobs||activity?.jobs||[];return <><div className="publish-layout"><Panel title="发布 Agent Package" description="租户 private 仅自己可见；public 仅当前租户可见。"><label className="field">可见范围<select value={visibility} onChange={e=>setVisibility(e.target.value as any)}><option value="private">个人私有</option><option value="public">租户内公开</option></select></label><label className="upload-zone"><span>↑</span><b>选择 Package</b><small>支持 .gz、.tgz、.tar.gz</small><input type="file" accept=".gz,.tgz,.tar.gz" onChange={e=>{const f=e.target.files?.[0];if(f)void client.publish(f,visibility).then(x=>setMessage(`发布任务 ${x.job_id} 已提交`)).catch(e=>setMessage(String(e)))}}/></label>{message&&<p className="notice">{message}</p>}</Panel><Panel title="Plugin 开发入口" description="使用短期开发 Token，在 Codex 或 Claude Code 中完成开发和发布。"><div className="plugin-card"><span>⌘</span><div><b>安装 Agentour Plugin</b><p>所有任务自动绑定当前租户和内部用户。</p></div></div><p className="muted">安装与使用说明由配套 Agentour Codex Plugin 提供。</p></Panel></div><Panel title="发布进度"><DataTable headers={["任务","状态","版本","更新时间"]} rows={(Array.isArray(jobs)?jobs:[]).map((x:any)=>[x.id||x.job_id,<Badge tone={x.status==="succeeded"?"success":x.status==="failed"?"danger":"warning"}>{x.status}</Badge>,x.version||"-",date(x.updated_at)])}/></Panel></>}

function Billing({client}:{client:AgentourClient}){const [personal,setPersonal]=useState<any>(),[tenant,setTenant]=useState<any>();useEffect(()=>{Promise.all([client.billing(),client.usage()]).then(([a,b])=>{setPersonal(a);setTenant(b)}).catch(()=>{})},[client]);if(!personal||!tenant)return <LoadingState/>;const ledger=personal.usage_ledger||personal.ledger||[],entries=tenant.entries||[];return <><div className="agentour-metrics"><MetricCard label="租户余额" value={tenant.tenant?.balance_credits||0} detail="积分"/><MetricCard label="个人记录" value={ledger.length}/><MetricCard label="租户用量记录" value={entries.length}/></div><Panel title="个人用量明细" description="仅当前内部用户"><DataTable headers={["时间","Agent","资源","积分"]} rows={ledger.map((x:any)=>[date(x.created_at||x.ts),x.agent_id||"-",x.resource_kind||x.note||"-",x.amount_credits??x.amount_cents??0])}/></Panel></>}

function Channels({client}:{client:AgentourClient}){const [rows,setRows]=useState<any[]|null>(null);useEffect(()=>{client.feishuStatus().then(x=>setRows(x.data||[])).catch(()=>setRows([]))},[client]);if(!rows)return <LoadingState/>;return <div className="channel-grid"><Panel title="飞书" description="统一使用 Agentour 飞书应用"><div className="channel-hero"><span>飞</span><div><h3>{rows.length?"已绑定":"等待绑定"}</h3><p>消息、Session 与消费均归属当前租户。</p></div><Badge tone={rows.length?"success":"warning"}>{rows.length?"运行中":"未安装"}</Badge></div>{rows.map(x=><dl className="summary-list" key={x.external_tenant_id}><div><dt>tenant_key</dt><dd>{x.external_tenant_id}</dd></div><div><dt>更新时间</dt><dd>{date(x.updated_at)}</dd></div></dl>)}</Panel><Panel title="渠道 Agent 范围" description="只允许租户获配且渠道启用的 Agent"><p className="muted">渠道范围由租户管理员配置，后端强制校验。</p></Panel></div>}

type AdminSection="overview"|"subjects"|"agents"|"runs"|"builds"|"storage"|"channels"|"audit";
const adminSections:{id:AdminSection;label:string}[]=[{id:"overview",label:"总览"},{id:"subjects",label:"内部用户"},{id:"agents",label:"Agent 与模型"},{id:"runs",label:"运行"},{id:"builds",label:"构建与评测"},{id:"storage",label:"存储"},{id:"channels",label:"渠道"},{id:"audit",label:"审计"}];
function Admin({client}:{client:AgentourClient}){const [section,setSection]=useState<AdminSection>("overview");return <div className="admin-shell"><nav className="admin-subnav">{adminSections.map(x=><button key={x.id} className={section===x.id?"active":""} onClick={()=>setSection(x.id)}>{x.label}</button>)}</nav><AdminContent section={section} client={client}/></div>}
function AdminContent({section,client}:{section:AdminSection;client:AgentourClient}){const [data,setData]=useState<any>(),[extra,setExtra]=useState<any>();useEffect(()=>{setData(undefined);const loaders:Record<AdminSection,()=>Promise<any>>={overview:()=>client.overview(),subjects:()=>client.subjects(),agents:()=>client.entitlements(),runs:()=>client.tenantSessions(),builds:()=>client.builds(),storage:()=>client.storage(),channels:()=>client.feishuStatus(),audit:()=>client.audit()};void loaders[section]().then(setData);if(section==="subjects")void client.subjectUsage().then(setExtra);if(section==="builds")void client.evals().then(setExtra)},[section,client]);if(!data)return <LoadingState/>;
 if(section==="overview"){const t=data.tenant||{},u=data.usage||{},r=data.resources||{};return <><div className="agentour-metrics"><MetricCard label="租户余额" value={t.balance_credits||0} detail="积分"/><MetricCard label="资源总数" value={r.total||0}/><MetricCard label="用量记录" value={(u.entries||[]).length}/><MetricCard label="租户状态" value={<Badge tone={t.status==="active"?"success":"danger"}>{t.status||"unknown"}</Badge>}/></div><Panel title="租户信息"><dl className="summary-list"><div><dt>名称</dt><dd>{t.name}</dd></div><div><dt>Slug</dt><dd>{t.slug}</dd></div><div><dt>能力</dt><dd>{Object.keys(t.capabilities||{}).filter(k=>t.capabilities[k]).join("、")||"-"}</dd></div></dl></Panel></>}
 if(section==="subjects"){const rows=data.data||[],usage=new Map((extra?.data||[]).map((x:any)=>[x.subject_id,x]));return <Panel title="内部用户" description="Agentour 只保存租户 Subject 映射，不管理密码或组织架构"><DataTable headers={["Subject","外部用户 ID","显示名","Session","积分","最近使用"]} rows={rows.map((x:any)=>{const u:any=usage.get(x.id)||{};return[x.id,x.external_subject_id,x.display_name||"-",u.sessions||0,u.credits||0,date(u.last_used_at||x.last_seen_at)]})}/></Panel>}
 if(section==="agents"){const agents=data.agents||[],models=data.models||[];return <div className="admin-two"><Panel title="Agent / AIO"><DataTable headers={["Agent","状态","版本策略"]} rows={agents.map((x:any)=>[x.agent_id,<Badge tone={x.enabled?"success":"danger"}>{x.enabled?"已启用":"已停用"}</Badge>,x.version_policy||"latest"])}/></Panel><Panel title="模型"><DataTable headers={["模型","状态"]} rows={models.map((x:any)=>[x.model_id,<Badge tone={x.enabled?"success":"danger"}>{x.enabled?"可用":"停用"}</Badge>])}/></Panel></div>}
 if(section==="runs")return <Panel title="Session 与运行"><DataTable headers={["Session","Subject","Agent","状态","积分","更新时间"]} rows={(data.data||[]).map((x:any)=>[x.id,x.subject_id||"-",x.agent_id,<Badge tone={x.state==="completed"?"success":"warning"}>{x.state}</Badge>,x.credits||0,date(x.updated_at)])}/></Panel>;
 if(section==="builds")return <div className="admin-two"><Panel title="Build"><DataTable headers={["任务","状态","Package"]} rows={(data.data||[]).map((x:any)=>[x.id,x.status,x.package_hash||"-"])}/></Panel><Panel title="Eval"><DataTable headers={["任务","Agent","状态","结论"]} rows={(extra?.data||[]).map((x:any)=>[x.id,x.agent_id,x.status,x.verdict||"-"])}/></Panel></div>;
 if(section==="storage")return <div className="agentour-metrics"><MetricCard label="Session" value={data.sessions||0}/><MetricCard label="Artifact" value={data.artifacts||0} detail={`${data.artifact_bytes||0} bytes`}/><MetricCard label="Attachment" value={data.attachments||0} detail={`${data.attachment_bytes||0} bytes`}/></div>;
 if(section==="channels")return <Panel title="渠道绑定"><DataTable headers={["渠道","外部租户","更新时间"]} rows={(data.data||[]).map((x:any)=>[x.provider,x.external_tenant_id,date(x.updated_at)])}/></Panel>;
 return <Panel title="审计事件"><DataTable headers={["时间","操作人","动作","目标"]} rows={(data.data||[]).map((x:any)=>[date(x.created_at),x.actor_id,x.action,`${x.target_type||""} ${x.target_id||""}`])}/></Panel>;
}
function date(value?:number){return value?new Date(value*1000).toLocaleString("zh-CN"):"-"}
