import { useEffect, useMemo, useState, type ReactNode } from "react";
import { AgentourClient, tokenFromEndpoint, type Agent, type LibraryItem, type Session, type TenantContext } from "./api";
import { portalConfig } from "./config";
import "./styles.css";

type Tab="discover"|"workspace"|"library"|"publish"|"billing"|"channels"|"admin";
const tabs:{id:Tab;label:string;admin?:boolean}[]=[{id:"discover",label:"发现"},{id:"workspace",label:"工作台"},{id:"library",label:"资料库"},{id:"publish",label:"我的发布"},{id:"billing",label:"账单"},{id:"channels",label:"渠道"},{id:"admin",label:"租户管理",admin:true}];

export default function App(){
 const config=useMemo(()=>portalConfig(),[]),client=useMemo(()=>new AgentourClient(config,()=>tokenFromEndpoint(config.tokenEndpoint)),[config]);
 const [context,setContext]=useState<TenantContext|null>(null),[agents,setAgents]=useState<Agent[]>([]),[tab,setTab]=useState<Tab>("discover"),[error,setError]=useState(""),[busy,setBusy]=useState(true),[sessionId,setSessionId]=useState("");
 const isAdmin=Boolean(context?.scopes.some(scope=>scope.startsWith("tenant:")));
 useEffect(()=>{document.documentElement.style.setProperty("--primary",config.primaryColor);Promise.all([client.context(),client.agents()]).then(([ctx,list])=>{setContext(ctx);setAgents(list.data)}).catch(e=>setError(String(e))).finally(()=>setBusy(false))},[client,config]);
 if(busy)return <main className="center"><div><div className="spinner"/><p>正在进入租户门户…</p></div></main>;
 if(error)return <main className="center"><section className="error"><h1>无法进入门户</h1><p>{error}</p><small>请确认租户登录系统已提供 {config.tokenEndpoint}</small></section></main>;
 return <div className="shell"><aside className="sidebar"><div className="brand">{config.brandLogo?<img src={config.brandLogo}/>:<span>⚡</span>}<div><b>{context?.tenant.name||config.brandName}</b><small>Agent 平台</small></div></div><nav>{tabs.filter(x=>!x.admin||isAdmin).map(x=><button key={x.id} className={tab===x.id?"active":""} onClick={()=>setTab(x.id)}>{x.label}</button>)}</nav><div className="balance"><small>租户余额</small><b>{context?.tenant.balance_credits?.toLocaleString()||0} 积分</b></div></aside>
 <main className="content"><header><div><small>租户专属工作区</small><h1>{tabs.find(x=>x.id===tab)?.label}</h1></div><div className="identity">{context?.actor_type}<br/><small>{context?.subject_id||"管理会话"}</small></div></header>
 {sessionId?<SessionView id={sessionId} client={client} onBack={()=>setSessionId("")}/>:<>{tab==="discover"&&<Discover agents={agents} client={client} onOpen={setSessionId}/>} {tab==="workspace"&&<Workspace client={client} onOpen={setSessionId}/>} {tab==="library"&&<Library client={client}/>} {tab==="publish"&&<Publishing client={client}/>} {tab==="billing"&&<Billing client={client}/>} {tab==="channels"&&<Channels client={client}/>} {tab==="admin"&&isAdmin&&<Admin client={client}/>}</>}</main></div>;
}
function Discover({agents,client,onOpen}:{agents:Agent[];client:AgentourClient;onOpen:(id:string)=>void}){const [q,setQ]=useState(""),[kind,setKind]=useState(""),[message,setMessage]=useState("");const rows=agents.filter(a=>(!q||`${a.name} ${a.description} ${(a.tags||[]).join(" ")}`.toLowerCase().includes(q.toLowerCase()))&&(!kind||a.kind===kind));return <><div className="toolbar"><input aria-label="搜索 Agent" placeholder="搜索名称、描述或标签" value={q} onChange={e=>setQ(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">全部类型</option>{[...new Set(agents.map(a=>a.kind).filter(Boolean))].map(x=><option key={x} value={x}>{x}</option>)}</select></div><section className="grid">{rows.map(a=><article className="card" key={a.id}><div className="agent-icon">{a.icon||"🤖"}</div><small>{a.kind||"Agent"}</small><h3>{a.name}</h3><p>{a.description||"租户可用 Agent"}</p><div className="tags">{(a.tags||[]).slice(0,4).map(t=><span key={t}>{t}</span>)}</div><button onClick={()=>client.createSession(a.id).then(x=>onOpen(x.session_id)).catch(e=>setMessage(String(e)))}>开始使用</button></article>)}</section>{!rows.length&&<p className="empty">没有匹配的 Agent</p>}{message&&<p className="notice">{message}</p>}</>}
function Workspace({client,onOpen}:{client:AgentourClient;onOpen:(id:string)=>void}){const [rows,setRows]=useState<Session[]>([]),[state,setState]=useState(""),[error,setError]=useState("");useEffect(()=>{client.sessions().then(x=>setRows(x.data)).catch(e=>setError(String(e)))},[client]);const filtered=rows.filter(x=>!state||x.state===state);return <section className="panel"><div className="panel-head"><h2>我的会话</h2><select value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option>{[...new Set(rows.map(x=>x.state))].map(x=><option key={x}>{x}</option>)}</select></div>{error?<p>{error}</p>:<Table headers={["会话","Agent","状态","消耗","操作"]} rows={filtered.map(x=>[x.title||x.id,x.agent_id,x.state,String(x.spent||0),<button onClick={()=>onOpen(x.id)}>打开</button>])}/>}</section>}
function SessionView({id,client,onBack}:{id:string;client:AgentourClient;onBack:()=>void}){const [data,setData]=useState<any>(),[text,setText]=useState(""),[error,setError]=useState("");const load=()=>Promise.all([client.session(id),client.presentation(id),client.artifacts(id)]).then(([session,presentation,artifacts])=>setData({session,presentation,artifacts})).catch(e=>setError(String(e)));useEffect(()=>{void load()},[id]);return <div><button className="back" onClick={onBack}>← 返回</button><div className="session-grid"><section className="panel"><div className="panel-head"><h2>{data?.session?.title||id}</h2><span className="status">{data?.session?.state||"加载中"}</span></div>{error&&<p className="error-text">{error}</p>}<div className="timeline">{(data?.presentation?.blocks||data?.presentation?.components||[]).map((x:any,i:number)=><article key={x.id||i}><small>{x.type||x.kind}</small><p>{x.text||x.content||x.title||JSON.stringify(x)}</p></article>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(text)client.sendMessage(id,text).then(()=>{setText("");load()}).catch(e=>setError(String(e)))}}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="给 Agent 发送消息"/><button>发送</button></form></section><aside className="panel"><h3>运行与交付物</h3><KeyValues value={data?.session}/><h3>Artifacts</h3>{(data?.artifacts?.data||[]).map((x:any)=><a className="artifact" key={x.id} href={`${portalConfig().apiBase}/v1/sdk/artifacts/${x.id}`}>{x.name||x.id}</a>)}<button className="danger" onClick={()=>client.cancel(id).then(load)}>取消运行</button></aside></div></div>}
function Library({client}:{client:AgentourClient}){const [rows,setRows]=useState<LibraryItem[]>([]),[q,setQ]=useState(""),[error,setError]=useState("");useEffect(()=>{client.library().then(x=>setRows(x.data)).catch(e=>setError(String(e)))},[client]);return <section className="panel"><div className="panel-head"><h2>我的资料</h2><input placeholder="搜索资料" value={q} onChange={e=>setQ(e.target.value)}/></div>{error?<p>{error}</p>:<Table headers={["名称","来源","更新时间"]} rows={rows.filter(x=>!q||(x.title||x.name||x.id).toLowerCase().includes(q.toLowerCase())).map(x=>[x.title||x.name||x.id,x.origin_kind||"-",x.updated_at?new Date(x.updated_at*1000).toLocaleString():"-"])}/>}</section>}
function Publishing({client}:{client:AgentourClient}){const [visibility,setVisibility]=useState<"private"|"public">("private"),[message,setMessage]=useState("");return <div className="admin-grid"><DataPanel title="我的 Agent" load={()=>client.developer()}/><section className="panel"><h2>上传 Agent Package</h2><p>公开仅表示租户内可见，不会向其他租户公开。</p><select value={visibility} onChange={e=>setVisibility(e.target.value as any)}><option value="private">仅自己</option><option value="public">租户内公开</option></select><input type="file" accept=".gz,.tgz,.tar.gz" onChange={e=>{const f=e.target.files?.[0];if(f)client.publish(f,visibility).then(x=>setMessage(`发布任务 ${x.job_id} 已提交`)).catch(err=>setMessage(String(err)))}}/>{message&&<p className="notice">{message}</p>}</section><DataPanel title="发布进度" load={()=>client.publishingActivity()}/></div>}
function Billing({client}:{client:AgentourClient}){return <div className="admin-grid"><DataPanel title="个人账单" load={()=>client.billing()}/><DataPanel title="租户用量归因" load={()=>client.usage()}/></div>}
function Channels({client}:{client:AgentourClient}){return <div className="admin-grid"><section className="panel"><h2>飞书</h2><p>由平台绑定飞书 tenant_key；消息、运行和计费均归属当前租户。</p></section><DataPanel title="绑定状态" load={()=>client.feishuStatus()}/></div>}
function Admin({client}:{client:AgentourClient}){const sections=[['总览',()=>client.overview()],['内部用户',()=>client.subjects()],['Agent 与模型',()=>client.entitlements()],['运行与存储',()=>client.resources()],['凭证',()=>client.serviceAccounts()],['审计事件',()=>client.audit()]] as const;return <div className="admin-grid">{sections.map(([title,load])=><DataPanel key={title} title={title} load={load}/>)}</div>}
function DataPanel({title,load}:{title:string;load:()=>Promise<any>}){const [data,setData]=useState<any>(),[error,setError]=useState("");useEffect(()=>{let active=true;load().then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[title]);return <section className="panel"><h2>{title}</h2>{error?<p className="error-text">{error}</p>:<KeyValues value={data}/>}</section>}
function KeyValues({value}:{value:any}){if(value==null)return <p className="empty">加载中…</p>;if(Array.isArray(value))return <Table headers={["数据"]} rows={value.map(x=>[typeof x==='object'?JSON.stringify(x):String(x)])}/>;if(typeof value==='object')return <dl className="kv">{Object.entries(value).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl>;return <p>{String(value)}</p>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return rows.length?<div className="table-wrap"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>:<p className="empty">暂无数据</p>}
