import { useEffect, useMemo, useState } from "react";
import { AgentourClient, tokenFromEndpoint, type Agent, type LibraryItem, type Session, type TenantContext } from "./api";
import { portalConfig } from "./config";
import "./styles.css";

type Tab="discover"|"workspace"|"library"|"publish"|"billing"|"channels"|"admin";
const tabs:{id:Tab;label:string;admin?:boolean}[]=[{id:"discover",label:"发现"},{id:"workspace",label:"工作台"},{id:"library",label:"资料库"},{id:"publish",label:"我的发布"},{id:"billing",label:"账单"},{id:"channels",label:"渠道"},{id:"admin",label:"租户管理",admin:true}];

export default function App(){
 const config=useMemo(()=>portalConfig(),[]),client=useMemo(()=>new AgentourClient(config,()=>tokenFromEndpoint(config.tokenEndpoint)),[config]);
 const [context,setContext]=useState<TenantContext|null>(null),[agents,setAgents]=useState<Agent[]>([]),[tab,setTab]=useState<Tab>("discover"),[error,setError]=useState(""),[busy,setBusy]=useState(true);
 const isAdmin=Boolean(context?.scopes.some(scope=>scope.startsWith("tenant:")));
 useEffect(()=>{document.documentElement.style.setProperty("--primary",config.primaryColor);Promise.all([client.context(),client.agents()]).then(([ctx,list])=>{setContext(ctx);setAgents(list.data)}).catch(e=>setError(String(e))).finally(()=>setBusy(false))},[client,config]);
 if(busy)return <main className="center"><div><div className="spinner"/><p>正在进入租户门户…</p></div></main>;
 if(error)return <main className="center"><section className="error"><h1>无法进入门户</h1><p>{error}</p><small>请确认租户登录系统已提供 {config.tokenEndpoint}</small></section></main>;
 return <div className="shell"><aside className="sidebar"><div className="brand">{config.brandLogo?<img src={config.brandLogo}/>:<span>⚡</span>}<div><b>{context?.tenant.name||config.brandName}</b><small>Agent 平台</small></div></div><nav>{tabs.filter(x=>!x.admin||isAdmin).map(x=><button key={x.id} className={tab===x.id?"active":""} onClick={()=>setTab(x.id)}>{x.label}</button>)}</nav><div className="balance"><small>租户余额</small><b>{context?.tenant.balance_credits?.toLocaleString()||0} 积分</b></div></aside>
 <main className="content"><header><div><small>租户专属工作区</small><h1>{tabs.find(x=>x.id===tab)?.label}</h1></div><div className="identity">{context?.actor_type}<br/><small>{context?.subject_id||"管理会话"}</small></div></header>
 {tab==="discover"&&<Discover agents={agents} client={client}/>} {tab==="workspace"&&<Workspace client={client}/>} {tab==="library"&&<Library client={client}/>} {tab==="publish"&&<Publishing client={client}/>} {tab==="billing"&&<JsonPanel title="积分流水" load={()=>client.billing()}/>} {tab==="channels"&&<Channels client={client}/>} {tab==="admin"&&isAdmin&&<Admin client={client}/>}</main></div>;
}
function Discover({agents,client}:{agents:Agent[];client:AgentourClient}){const [message,setMessage]=useState("");return <><p className="lead">这里只展示平台分配给本租户，以及本租户内部公开的 Agent。</p><section className="grid">{agents.map(a=><article className="card" key={a.id}><div className="agent-icon">{a.icon||"🤖"}</div><h3>{a.name}</h3><p>{a.description||"租户可用 Agent"}</p><div className="tags">{(a.tags||[]).slice(0,3).map(t=><span key={t}>{t}</span>)}</div><button onClick={()=>client.createSession(a.id).then(x=>setMessage(`已创建会话 ${x.session_id}`)).catch(e=>setMessage(String(e)))}>开始使用</button></article>)}</section>{message&&<p className="notice">{message}</p>}</>}
function Workspace({client}:{client:AgentourClient}){const [rows,setRows]=useState<Session[]>([]),[error,setError]=useState("");useEffect(()=>{client.sessions().then(x=>setRows(x.data)).catch(e=>setError(String(e)))},[client]);return <section className="panel"><h2>我的会话</h2>{error?<p>{error}</p>:<Table headers={["会话","Agent","状态","消耗"]} rows={rows.map(x=>[x.title||x.id,x.agent_id,x.state,String(x.spent||0)])}/>}</section>}
function Library({client}:{client:AgentourClient}){const [rows,setRows]=useState<LibraryItem[]>([]),[error,setError]=useState("");useEffect(()=>{client.library().then(x=>setRows(x.data)).catch(e=>setError(String(e)))},[client]);return <section className="panel"><h2>我的资料</h2>{error?<p>{error}</p>:<Table headers={["名称","来源","更新时间"]} rows={rows.map(x=>[x.title||x.name||x.id,x.origin_kind||"-",x.updated_at?new Date(x.updated_at*1000).toLocaleString():"-"])}/>}</section>}
function Publishing({client}:{client:AgentourClient}){const [visibility,setVisibility]=useState<"private"|"public">("private"),[message,setMessage]=useState("");return <div className="admin-grid"><JsonPanel title="我的 Agent" load={()=>client.developer()}/><section className="panel"><h2>上传 Agent Package</h2><p>“公开”仅表示租户内所有用户可见；其他租户和平台普通用户不可见。</p><select value={visibility} onChange={e=>setVisibility(e.target.value as "private"|"public")}><option value="private">仅自己</option><option value="public">租户内公开</option></select><input type="file" accept=".gz,.tgz,.tar.gz" onChange={e=>{const f=e.target.files?.[0];if(f)client.publish(f,visibility).then(x=>setMessage(`发布任务 ${x.job_id} 已提交`)).catch(err=>setMessage(String(err)))}}/>{message&&<p className="notice">{message}</p>}</section><JsonPanel title="发布进度" load={()=>client.publishingActivity()}/></div>}
function Channels({client}:{client:AgentourClient}){return <div className="admin-grid"><section className="panel"><h2>飞书</h2><p>现阶段统一安装 Agentour 飞书应用。平台管理员把飞书 tenant_key 绑定到本租户后，消息由 Agentour 运行并计入租户钱包。</p></section><JsonPanel title="我的绑定状态" load={()=>client.feishuStatus()}/></div>}
function Admin({client}:{client:AgentourClient}){return <div className="admin-grid"><JsonPanel title="租户用量（按内部用户归因）" load={()=>client.usage()}/><JsonPanel title="租户审计事件" load={()=>client.audit()}/></div>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return rows.length?<div className="table-wrap"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>:<p className="empty">暂无数据</p>}
function JsonPanel({title,load}:{title:string;load:()=>Promise<unknown>}){const [data,setData]=useState<unknown>(),[error,setError]=useState("");useEffect(()=>{load().then(setData).catch(e=>setError(String(e)))},[]);return <section className="panel"><h2>{title}</h2>{error?<p>{error}</p>:<pre>{JSON.stringify(data,null,2)}</pre>}</section>}
